apiVersion: v1

kind: Pod

metadata:
  name: nginx
  labels:
    env: production

spec:
  containers:
    - name: nginx
      image: private-registry.io/apps/internal-app

  imagePullSecrets:
    - name: regcred