apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-vol1

spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi

  # hostPath: 
  #     path: /data
  #     type: Directory 

  # awsElasticBlockStore:
  #     volumeID: <volume-id>
  #     fsType: ext4