apiVersion: v1

kind: PersistentVolume

metadata: 
  name: pv-log

spec: 
  accessModes: 
    - ReadWriteMany

  hostPath: 
    path: /pv/log

  persistentVolumeReclaimPolicy: Retain

  capacity: 
    storage: 100Mi