apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
spec: 
  container:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env: # List of Environment variables
        - name: APP_COLOR
          value: pink