apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
spec:
  containers:
    - name: nginx
      image: nginx 
      securityContext: 
        runAsUser: 1000
      capabilities: 
        add: ["MAC_ADMIN"]