apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
  labels:
    name: random-number-generator
spec:
  containers:
  - name: random-number-generator
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
    command: ["/bin/sh", "c"]
    args: ["shuf -i 0-100 -n 1"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: myclaim