apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
spec: 
  container:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef: 
            name: app-secret
---
apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color1
spec: 
  container:
    - name: simple-webapp-color1
      image: simple-webapp-color1
      ports:
        - containerPort: 8080
      env:
        - name: DB_Password
          secretKeyRef: 
            name: app-secret
            key: DB_Password
---
apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color1
spec: 
  container:
    - name: simple-webapp-color1
      image: simple-webapp-color1
      ports:
        - containerPort: 8080
  volumes:
    - name: app-secret-volume
      secret: 
        secretName: app-secret